### ISSUE TITLE
Request to add the destroy action in the CommentsController

### ISSUE THREAD

**Issue by mnong** [railscrashcourse/blog#1]
I would be thankful if you could add the destroy action in the CommentsController in blog-ch5

**Comment by anthonylewis** [comment]
Sure, no problem. I'll create a branch this weekend and add the `destroy` action.

**Comment by anthonylewis** [comment]
I created a new branch called [comments-destroy](https://github.com/railscrashcourse/blog/tree/comments-destroy) and added the destroy action.

Here are the steps I followed:
1. Update `config/routes.rb` to include a route for comments destroy
2. Add a `destroy` method to `app/controllers/comments_controller.rb`
3. Add a _Destroy_ link to the comment partial at `app/views/comments/_comment.html.erb`

The changes are in this commit: https://github.com/railscrashcourse/blog/commit/f41049690b62b0661cb7f47f565a3e3609490039

Hope this helps!

**Comment by mnong** [comment]
I had this in my comment partial :

<%= link_to 'Destroy', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' } %>

That threw a nasty error page. I used your code :

<%= link_to 'Destroy', post_comment_path(comment.post, comment), method: :delete, data: { confirm: 'Are you sure?' } %>

but I still get an error, something like:

No route matches [GET] "/posts/5/comments/5"

And now I can't even destroy a post which is not having comments!

Here's my repo (unfixed) : https://github.com/mnong/myblog

Can you tell me what's wrong with my code?

**Comment by anthonylewis** [comment]
That's strange, it works for me either way. I'll clone your repo and see if I can figure it out.

**Comment by anthonylewis** [comment]
I see the problem. In your application layout you commented out the JavaScript include tag:

https://github.com/mnong/myblog/blob/master/app/views/layouts/application.html.erb#L7

That `link_to` helper uses unobtrusive JavaScript to set the request to `DELETE` instead of `GET`. That's why you're seeing the error message that mentions the `GET` request.

Add the `javascript_include_tag` back and everything should work.

**Comment by anthonylewis** [comment]
Also, for anyone else reading this, this is Exercise 3 at the end of Chapter 5. The answers to all exercises are in the back of the book.

**Comment by mnong** [comment]
I had to comment that line as I was getting this error (my dev m/c is Windows, if that helps) 

ExecJS::ProgramError in Posts#index
Showing C:/railsapp/myblog/app/views/layouts/application.html.erb where line #7 raised:

TypeError: Object doesn't support this property or method
  (in C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/gems/turbolinks-2.5.3/lib/assets/javascripts/turbolinks.js.coffee)

Any workarounds?

**Comment by columbusguy65** [comment]
I'm doing the Social application in your book. I'm using Rails 4.2. When I try to run the db:migrate after generating the model for Subscription I get the following error:

Raven:social$ rails g model Subscription leader:references follower:references
      invoke  active_record
      create    db/migrate/20150930181731_create_subscriptions.rb
      create    app/models/subscription.rb
      invoke    test_unit
      create      test/models/subscription_test.rb
      create      test/fixtures/subscriptions.yml
Raven:migrate bnadvornik$ rake db:migrate
(in /Users/.../projects/social)
== 20150930181731 CreateSubscriptions: migrating ==============================
-- create_table(:subscriptions)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "leaders" does not exist
: ALTER TABLE "subscriptions" ADD CONSTRAINT "fk_rails_7b4891a3a6"
FOREIGN KEY ("leader_id")
  REFERENCES "leaders" ("id")

Any help or ideas would be awesome.

Bill
